---

- name: Update apt
  become: true
  apt:
    upgrade: yes
    update_cache: yes

- name: Install required system packages
  become: true
  apt:
    name: "{{ packages }}"
    state: present

- name: Install apache
  apt:
    name=apache2
    state=latest

- name: Update /etc/hosts
  ansible.builtin.shell: |
    echo "{{ web1host }}" web1 >> /etc/hosts
    echo "{{ web2host }}" web2 >> /etc/hosts
    echo "{{ back1host }}" back1 >> /etc/hosts
    echo "{{ back2host }}" back2 >> /etc/hosts
    echo "{{ viphost }}" VipLb >> /etc/hosts

- name: started apache2
  become: true
  service:
    name: apache2
    state: started

...