---

- name: Правим index.html на backend1
  ansible.builtin.shell: echo '<h1>Это backend1"</h1>' > /var/www/html/index.html

- name: restart apache2
  become: true
  service:
    name: apache2
    state: restarted

...