version: "3.7"
services:

  web1:
    container_name: web1
    user: root
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "81:80"
    cap_add:
      - NET_ADMIN
    networks:
      app_net:
        ipv4_address: 172.16.0.2

  web2:
    container_name: web2
    user: root
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "82:80"
    cap_add:
     - NET_ADMIN
    networks:
      app_net:
        ipv4_address: 172.16.0.3

  bec1:
    container_name: bec1
    user: root
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "83:80"
    networks:
      app_net:
        ipv4_address: 172.16.0.4
  bec2:
    container_name: bec2
    user: root
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "84:80"
    networks:
      app_net:
        ipv4_address: 172.16.0.5

  ansible:
    container_name: ansible
    user: root    
    command: bash -c "
        apt-get update -y
        && apt install -y gcc libkrb5-dev
        && apt install python3-pip -y
        && apt install openssh-client -y
        && apt install python3.10-venv -y
        && apt install sshpass -y
        && pip3 install --upgrade pip
        && pip3 install --upgrade virtualenv
        && pip3 install ansible
        && /usr/sbin/sshd -D 
      "
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "85:80"
    networks:
      app_net:
        ipv4_address: 172.16.0.6

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24
