---

- name: Отключаем STONITH и ибудем игнорировать политику кворума
  ansible.builtin.shell: |
    crm configure property stonith-enabled=false
    crm configure property no-quorum-policy=ignore

- name: конфигирируем vip
  ansible.builtin.shell: |
    crm configure primitive virtual_ip ocf:heartbeat:IPaddr2 params ip="172.16.0.10" cidr_netmask="24" op monitor interval="10s" meta migration-threshold="10"
    crm configure group vipLb_balancing virtual_ip

...